apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-enem-estado
  namespace: airflow
spec:
  volumes:
    - name: ivy
      emptyDir: {}
      configMap:
      name:
  sparkConf:
    spark.kubernetes.allocation.batch.size: "10"
    google.cloud.auth.service.account.email: "mateusc.lira@gmail.com"
    spark.hadoop.fs.gs.project.id: "igti-edc-mod4"
  hadoopConf:
    "fs.gs.project.id": "igti-edc-mod4"
    "fs.gs.system.bucket": "igti-edc-mod4-gs://mateus-processing-zone"
    "fs.gs.system.bucket": "igti-edc-mod4-gs://mateus-landing-zone"
    "google.cloud.auth.service.account.enable": "true"
    "google.cloud.auth.service.account.json.keyfile": "./mateusclira.json"
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "mesosphere/spark-operator:3.1.1-1.1.17"
  imagePullPolicy: Always
  mainApplicationFile: gs://mateus-codigos-pyspark/enem_agrega_estado.py
  sparkVersion: "3.1.1"
  restartPolicy:
    type: Never
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "8g"
    labels:
      version: 3.1.1
    serviceAccount: airflow-worker
    volumeMounts:
      - name: ivy
        mountPath: /tmp
  executor:
    cores: 3
    instances: 3
    memory: "8g"
    labels:
      version: 3.1.1
    volumeMounts:
      - name: ivy
        mountPath: /tmp